In [17]:
from model import *
import pandas as pd
from tqdm import tqdm

N_STEPS = 10

In [18]:
F = {
    'L': 0.5,
    'M': 0.4,
    'H': 0.1
}


gamma = {
    'L': 0.00111708,
    'M': 0.00134359,
    'H': 0.00133346
}

In [19]:
start_dist = pd.read_csv("../export/sim/class_distribution_MILANO_2011.csv")
model = PopWeightedModel(start_dist, F, gamma)

In [20]:
model.cld

    geom_id  year   pop cl
0      ZurM  2011  6030  L
1      ZurM  2011  5880  M
2      ZurM  2011  2123  H
3      Ltnp  2011  2723  L
4      Ltnp  2011  2540  M
..      ...   ...   ... ..
241    JwSa  2011  5555  M
242    JwSa  2011   766  H
243    XoTb  2011  2324  L
244    XoTb  2011  2020  M
245    XoTb  2011   249  H

[246 rows x 4 columns]

In [21]:
for s in tqdm(range(N_STEPS)):
    model.step()

  0%|          | 0/10 [00:00<?, ?it/s]

100%|██████████| 10/10 [00:05<00:00,  1.98it/s]

In [22]:
model.cld

    geom_id  year   pop cl
0      ZurM  2021  6110  L
1      ZurM  2021  5960  M
2      ZurM  2021  2143  H
3      Ltnp  2021  2753  L
4      Ltnp  2021  2570  M
..      ...   ...   ... ..
241    JwSa  2021  5625  M
242    JwSa  2021   786  H
243    XoTb  2021  2354  L
244    XoTb  2021  2050  M
245    XoTb  2021   259  H

[246 rows x 4 columns]

In [23]:
target = pd.read_csv("../export/sim/class_distribution_MILANO_2021.csv").sort_values("geom_id")

In [24]:
model.hist[0].sort_values(["P_tot", "inflow"], ascending=False)

     P_tot        R cl         f geom_id     inflow    outflow    pop  year
180  88441  88441.0  L  0.482887    yStd  47.787031  47.707136  42707  2011
181  88441  88441.0  M  0.407413    yStd  45.854000  48.412235  36032  2011
182  88441  88441.0  H  0.109700    yStd  11.324345  12.937229   9702  2011
231  59601  59601.0  L  0.524253    EdJh  32.664467  34.904282  31246  2011
232  59601  59601.0  M  0.415245    EdJh  31.441992  33.252509  24749  2011
..     ...      ... ..       ...     ...        ...        ...    ...   ...
193   3083   3083.0  M  0.445021    E14h   1.681528   1.843405   1372  2011
194   3083   3083.0  H  0.072981    E14h   0.417290   0.300029    225  2011
48    2531   2531.0  L  0.419202    lUwi   1.435663   1.185222   1061  2011
49    2531   2531.0  M  0.388779    lUwi   1.381183   1.322093    984  2011
50    2531   2531.0  H  0.192019    lUwi   0.342091   0.648062    486  2011

[246 rows x 9 columns]

In [25]:
from optimize import *

In [26]:
cost_function(target, model.cld)

np.int64(117047150)

In [27]:
model.cld.sort_values("geom_id")

    geom_id  year    pop cl
84     2BL6  2021  15138  L
85     2BL6  2021   9743  M
86     2BL6  2021   2130  H
147    31yf  2021  16407  L
148    31yf  2021  14019  M
..      ...   ...    ... ..
183    z2Nl  2021   8838  L
184    z2Nl  2021   7057  M
125    zYFB  2021   2551  H
123    zYFB  2021  23300  L
124    zYFB  2021  17347  M

[246 rows x 4 columns]

In [28]:
target

    geom_id  year    pop cl
84     2BL6  2021  15728  L
85     2BL6  2021  10162  M
86     2BL6  2021   2081  H
147    31yf  2021  16977  L
148    31yf  2021  14994  M
..      ...   ...    ... ..
183    z2Nl  2021   9051  L
184    z2Nl  2021   7078  M
125    zYFB  2021   2328  H
123    zYFB  2021  22605  L
124    zYFB  2021  16391  M

[246 rows x 4 columns]